#!/usr/bin/env python3
"""
html_export.py

HTML export module for OOMKilled / CrashLoopBackOff detector.
Generates a standalone HTML report that can be opened directly in a browser.
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Dict, Any
import html


def escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return html.escape(str(text))


def generate_html_report(
    rows: List[Dict[str, str]],
    time_range_str: str,
    html_path: Path,
) -> None:
    """
    Generate a standalone HTML report from collected rows.
    
    Args:
        rows: List of dictionaries representing OOM/CrashLoopBackOff findings
        time_range_str: Time range string used for detection (e.g., "1d", "6h")
        html_path: Path where HTML file should be written
    """
    if not rows:
        # Generate empty report
        html_content = _generate_empty_html(time_range_str)
    else:
        html_content = _generate_html_with_data(rows, time_range_str)
    
    try:
        html_path.write_text(html_content, encoding='utf-8')
    except (IOError, OSError) as e:
        raise IOError(f"Failed to write HTML file {html_path}: {e}")


def _generate_empty_html(time_range_str: str) -> str:
    """Generate HTML for empty results."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OOM / CrashLoopBackOff Report - No Issues Found</title>
    <style>
        {_get_css_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>OOM / CrashLoopBackOff Detection Report</h1>
            <div class="metadata">
                <span class="badge badge-success">No Issues Found</span>
                <span class="badge badge-info">Time Range: {escape_html(time_range_str)}</span>
            </div>
        </header>
        <main>
            <div class="empty-state">
                <p>✅ No OOMKilled or CrashLoopBackOff pods detected in the specified time range.</p>
            </div>
        </main>
    </div>
</body>
</html>"""


def _generate_html_with_data(rows: List[Dict[str, str]], time_range_str: str) -> str:
    """Generate HTML report with data."""
    # Count statistics
    total_findings = len(rows)
    oom_count = sum(1 for r in rows if r.get("type") == "OOMKilled")
    crash_count = sum(1 for r in rows if r.get("type") == "CrashLoopBackOff")
    
    # Generate summary table
    summary_table = _generate_summary_table(rows)
    
    # Generate detailed findings table (flat table matching oom_results.table format)
    details_table = _generate_details_table(rows)
    
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OOM / CrashLoopBackOff Report</title>
    <style>
        {_get_css_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>OOM / CrashLoopBackOff Detection Report</h1>
            <div class="metadata">
                <span class="badge badge-danger">Total Findings: {total_findings}</span>
                <span class="badge badge-warning">OOMKilled: {oom_count}</span>
                <span class="badge badge-warning">CrashLoopBackOff: {crash_count}</span>
                <span class="badge badge-info">Time Range: {escape_html(time_range_str)}</span>
            </div>
        </header>
        <main>
            <section class="summary-section">
                <h2>Summary</h2>
                {summary_table}
            </section>
            <section class="details-section">
                <h2>Detailed Findings</h2>
                {details_table}
            </section>
        </main>
        <footer>
            <p>Report generated by oc_get_ooms.py</p>
        </footer>
    </div>
    <script>
        {_get_sorting_javascript()}
    </script>
</body>
</html>"""


def _generate_summary_table(rows: List[Dict[str, str]]) -> str:
    """Generate summary statistics table."""
    # Count by cluster and type
    cluster_stats = {}
    for row in rows:
        cluster = row.get("cluster", "unknown")
        issue_type = row.get("type", "unknown")
        if cluster not in cluster_stats:
            cluster_stats[cluster] = {"OOMKilled": 0, "CrashLoopBackOff": 0}
        cluster_stats[cluster][issue_type] = cluster_stats[cluster].get(issue_type, 0) + 1
    
    table_rows = []
    for cluster in sorted(cluster_stats.keys()):
        stats = cluster_stats[cluster]
        total = stats["OOMKilled"] + stats["CrashLoopBackOff"]
        table_rows.append(f"""
            <tr>
                <td>{escape_html(cluster)}</td>
                <td class="number">{stats['OOMKilled']}</td>
                <td class="number">{stats['CrashLoopBackOff']}</td>
                <td class="number"><strong>{total}</strong></td>
            </tr>""")
    
    return f"""
        <table class="summary-table">
            <thead>
                <tr>
                    <th>Cluster</th>
                    <th>OOMKilled</th>
                    <th>CrashLoopBackOff</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {''.join(table_rows)}
            </tbody>
        </table>"""


def _generate_details_table(rows: List[Dict[str, str]]) -> str:
    """Generate detailed findings table matching oom_results.table format."""
    table_rows = []
    for row in rows:
        cluster = escape_html(row.get("cluster", ""))
        namespace = escape_html(row.get("namespace", ""))
        pod = escape_html(row.get("pod", ""))
        issue_type = row.get("type", "")
        timestamps = escape_html(row.get("timestamps", ""))
        sources = escape_html(row.get("sources", ""))
        desc_file = escape_html(row.get("description_file", ""))
        log_file = escape_html(row.get("pod_log_file", ""))
        time_range = escape_html(row.get("time_range", ""))
        
        # Type badge
        type_class = "badge-oom" if issue_type == "OOMKilled" else "badge-crash"
        type_badge = f'<span class="badge {type_class}">{escape_html(issue_type)}</span>'
        
        # File links
        desc_link = f'<a href="file://{desc_file}" class="file-link" title="{desc_file}">View</a>' if desc_file else "<em>N/A</em>"
        log_link = f'<a href="file://{log_file}" class="file-link" title="{log_file}">View</a>' if log_file else "<em>N/A</em>"
        
        table_rows.append(f"""
            <tr>
                <td>{cluster}</td>
                <td>{namespace}</td>
                <td class="pod-name">{pod}</td>
                <td class="pod-type">{type_badge}</td>
                <td class="pod-timestamps">{timestamps}</td>
                <td class="pod-sources">{sources}</td>
                <td class="pod-files">{desc_link}</td>
                <td class="pod-files">{log_link}</td>
                <td>{time_range}</td>
            </tr>""")
    
    return f"""
        <table class="details-table sortable">
            <thead>
                <tr>
                    <th class="sortable-header" data-sort="text">Cluster <span class="sort-indicator">↕</span></th>
                    <th class="sortable-header" data-sort="text">Namespace <span class="sort-indicator">↕</span></th>
                    <th class="sortable-header" data-sort="text">Pod <span class="sort-indicator">↕</span></th>
                    <th class="sortable-header" data-sort="text">Type <span class="sort-indicator">↕</span></th>
                    <th class="sortable-header" data-sort="text">Timestamps <span class="sort-indicator">↕</span></th>
                    <th class="sortable-header" data-sort="text">Sources <span class="sort-indicator">↕</span></th>
                    <th class="sortable-header" data-sort="text">Description File <span class="sort-indicator">↕</span></th>
                    <th class="sortable-header" data-sort="text">Pod Log File <span class="sort-indicator">↕</span></th>
                    <th class="sortable-header" data-sort="text">Time Range <span class="sort-indicator">↕</span></th>
                </tr>
            </thead>
            <tbody>
                {''.join(table_rows)}
            </tbody>
        </table>"""


def _get_css_styles() -> str:
    """Return CSS styles for the HTML report."""
    return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background-color: #f5f5f5;
            color: #333;
            line-height: 1.6;
            padding: 20px;
        }
        
        .container {
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        
        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }
        
        header h1 {
            font-size: 2em;
            margin-bottom: 15px;
        }
        
        .metadata {
            display: flex;
            justify-content: center;
            gap: 10px;
            flex-wrap: wrap;
            margin-top: 15px;
        }
        
        .badge {
            display: inline-block;
            padding: 6px 12px;
            border-radius: 4px;
            font-size: 0.9em;
            font-weight: 600;
        }
        
        .badge-success {
            background-color: #10b981;
            color: white;
        }
        
        .badge-danger {
            background-color: #ef4444;
            color: white;
        }
        
        .badge-warning {
            background-color: #f59e0b;
            color: white;
        }
        
        .badge-info {
            background-color: #3b82f6;
            color: white;
        }
        
        .badge-oom {
            background-color: #dc2626;
            color: white;
        }
        
        .badge-crash {
            background-color: #ea580c;
            color: white;
        }
        
        main {
            padding: 30px;
        }
        
        section {
            margin-bottom: 40px;
        }
        
        h2 {
            color: #1f2937;
            margin-bottom: 20px;
            font-size: 1.5em;
            border-bottom: 2px solid #e5e7eb;
            padding-bottom: 10px;
        }
        
        .empty-state {
            text-align: center;
            padding: 60px 20px;
            color: #6b7280;
            font-size: 1.2em;
        }
        
        .summary-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            background: white;
        }
        
        .summary-table th,
        .summary-table td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #e5e7eb;
        }
        
        .summary-table th {
            background-color: #f9fafb;
            font-weight: 600;
            color: #374151;
        }
        
        .summary-table tr:hover {
            background-color: #f9fafb;
        }
        
        .number {
            text-align: right;
            font-family: 'Courier New', monospace;
        }
        
        .details-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            background: white;
            font-size: 0.9em;
        }
        
        .details-table th,
        .details-table td {
            padding: 10px 12px;
            text-align: left;
            border-bottom: 1px solid #e5e7eb;
        }
        
        .details-table th {
            background-color: #f9fafb;
            font-weight: 600;
            color: #374151;
            position: sticky;
            top: 0;
            z-index: 10;
        }
        
        .sortable-header {
            cursor: pointer;
            user-select: none;
            position: relative;
            padding-right: 25px !important;
        }
        
        .sortable-header:hover {
            background-color: #e5e7eb !important;
        }
        
        .sort-indicator {
            position: absolute;
            right: 8px;
            font-size: 0.8em;
            color: #6b7280;
        }
        
        .sortable-header.sort-asc .sort-indicator::after {
            content: " ↑";
            color: #3b82f6;
        }
        
        .sortable-header.sort-desc .sort-indicator::after {
            content: " ↓";
            color: #3b82f6;
        }
        
        .sortable-header.sort-asc .sort-indicator,
        .sortable-header.sort-desc .sort-indicator {
            display: none;
        }
        
        .details-table tr:hover {
            background-color: #f9fafb;
        }
        
        .details-table .pod-name {
            font-family: 'Courier New', monospace;
            font-weight: 600;
            color: #1f2937;
        }
        
        .details-table .pod-type {
            text-align: center;
        }
        
        .details-table .pod-timestamps {
            font-size: 0.9em;
            color: #6b7280;
            white-space: pre-wrap;
        }
        
        .details-table .pod-sources {
            font-size: 0.85em;
            color: #6b7280;
            font-family: 'Courier New', monospace;
        }
        
        .details-table .pod-files {
            font-size: 0.85em;
        }
        
        .file-link {
            color: #3b82f6;
            text-decoration: none;
            padding: 4px 8px;
            border-radius: 3px;
            display: inline-block;
            transition: background-color 0.2s;
        }
        
        .file-link:hover {
            background-color: #dbeafe;
            text-decoration: underline;
        }
        
        footer {
            background-color: #f9fafb;
            padding: 20px;
            text-align: center;
            color: #6b7280;
            font-size: 0.9em;
            border-top: 1px solid #e5e7eb;
        }
        
        @media (max-width: 768px) {
            body {
                padding: 10px;
            }
            
            header h1 {
                font-size: 1.5em;
            }
            
            .metadata {
                flex-direction: column;
                align-items: center;
            }
            
            .details-table {
                font-size: 0.75em;
                display: block;
                overflow-x: auto;
            }
            
            .details-table th,
            .details-table td {
                padding: 6px 8px;
            }
        }
    """


def _get_sorting_javascript() -> str:
    """Return JavaScript code for table sorting functionality."""
    return """
        (function() {
            function makeSortable(table) {
                const headers = table.querySelectorAll('.sortable-header');
                let currentSort = { column: null, direction: 'asc' };
                
                headers.forEach((header, index) => {
                    header.addEventListener('click', function() {
                        const column = index;
                        const direction = currentSort.column === column && currentSort.direction === 'asc' ? 'desc' : 'asc';
                        
                        // Remove sort classes from all headers
                        headers.forEach(h => {
                            h.classList.remove('sort-asc', 'sort-desc');
                        });
                        
                        // Add sort class to current header
                        header.classList.add(direction === 'asc' ? 'sort-asc' : 'sort-desc');
                        
                        // Sort the table
                        sortTable(table, column, direction);
                        
                        // Update current sort
                        currentSort = { column, direction };
                    });
                });
            }
            
            function sortTable(table, column, direction) {
                const tbody = table.querySelector('tbody');
                const rows = Array.from(tbody.querySelectorAll('tr'));
                
                rows.sort((a, b) => {
                    const aText = a.cells[column].textContent.trim();
                    const bText = b.cells[column].textContent.trim();
                    
                    // Try to parse as number first
                    const aNum = parseFloat(aText);
                    const bNum = parseFloat(bText);
                    
                    let comparison = 0;
                    if (!isNaN(aNum) && !isNaN(bNum)) {
                        // Both are numbers
                        comparison = aNum - bNum;
                    } else {
                        // String comparison (case-insensitive)
                        comparison = aText.localeCompare(bText, undefined, { 
                            numeric: true, 
                            sensitivity: 'base' 
                        });
                    }
                    
                    return direction === 'asc' ? comparison : -comparison;
                });
                
                // Remove all rows from tbody
                rows.forEach(row => tbody.removeChild(row));
                
                // Add sorted rows back
                rows.forEach(row => tbody.appendChild(row));
            }
            
            // Initialize sorting when page loads
            document.addEventListener('DOMContentLoaded', function() {
                const table = document.querySelector('.sortable');
                if (table) {
                    makeSortable(table);
                }
            });
            
            // Also try immediately in case DOMContentLoaded already fired
            const table = document.querySelector('.sortable');
            if (table && table.querySelector('tbody')) {
                makeSortable(table);
            }
        })();
    """
