local grafonnet = import 'github.com/grafana/grafonnet/gen/grafonnet-latest/main.libsonnet';
local probes = import 'probes.libsonnet';

// Just some shortcuts
local dashboard = grafonnet.dashboard;
local row = grafonnet.panel.row;

// Define dashboard variables
local datasourceVar = probes.datasourceVar();
local memberClusterVar_data = [
  'https://api.kfluxfedorap01.toli.p1.openshiftapps.com:6443/',
  'https://api.kflux-ocp-p01.7ayg.p1.openshiftapps.com:6443/',
  'https://api.kflux-prd-rh02.0fk9.p1.openshiftapps.com:6443/',
  'https://api.kflux-prd-rh03.nnv1.p1.openshiftapps.com:6443/',
  'https://api.kflux-rhel-p01.fc38.p1.openshiftapps.com:6443/',
  'https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443/',
  'https://api.stone-prod-p01.wcfb.p1.openshiftapps.com:6443/',
  'https://api.stone-prod-p02.hjvn.p1.openshiftapps.com:6443/',
  'https://api.stone-stage-p01.hpmt.p1.openshiftapps.com:6443/',
  'https://api.stone-stg-rh01.l2vh.p1.openshiftapps.com:6443/',
];
local memberClusterVar = probes.memberClusterVar(memberClusterVar_data);
local smoothingVar = probes.smoothingVar();

dashboard.new('Konflux clusters loadtest probe results')
+ dashboard.withUid('Konflux_clusters_loadtest_probe_results')
+ dashboard.withDescription('Dashboard visualizes Konflux clusters loadtest probe results. Related Horreum test is https://horreum.corp.redhat.com/test/372 with filter by label `.repo_type = nodejs-devfile-sample`.')
+ dashboard.time.withFrom(value='now-7d')
+ dashboard.withVariables([
  datasourceVar,
  memberClusterVar,
  smoothingVar,
])
+ dashboard.withPanels([
  // Main panels
  row.new('KPI durations'),
  probes.durationsPanel(372, ['__results_measurements_KPI_mean'], 's', 'Mean duration'),
  row.new('KPI errors'),
  probes.errorsCountPanel(372, ['__results_measurements_KPI_errors'], 'Failure rate'),
  row.new('Errors table'),
  probes.errorsTablePanel(372),
  row.new('Errors pie-chart'),
  probes.errorsPiePanel(372),
  // Panels splitting test actions
  row.new('Duration by test phase'),
  probes.durationsPanel(372, [
    '__results_measurements_HandleUser_pass_duration_mean',
    '__results_measurements_createApplication_pass_duration_mean',
    '__results_measurements_createComponent_pass_duration_mean',
    '__results_measurements_createIntegrationTestScenario_pass_duration_mean',
    '__results_measurements_createReleasePlanAdmission_pass_duration_mean',
    '__results_measurements_createReleasePlan_pass_duration_mean',
    '__results_measurements_getPaCPullNumber_pass_duration_mean',
    '__results_measurements_validateApplication_pass_duration_mean',
    '__results_measurements_validateComponentBuildSA_pass_duration_mean',  // TODO: Delme later, I was renamed to just __results_measurements_validateComponent_...
    '__results_measurements_validateComponent_pass_duration_mean',
    '__results_measurements_validateIntegrationTestScenario_pass_duration_mean',
    '__results_measurements_validatePipelineRunCondition_pass_duration_mean',
    '__results_measurements_validatePipelineRunCreation_pass_duration_mean',
    '__results_measurements_validatePipelineRunSignature_pass_duration_mean',
    '__results_measurements_validateReleaseCondition_pass_duration_mean',
    '__results_measurements_validateReleaseCreation_pass_duration_mean',
    '__results_measurements_validateReleasePipelineRunCondition_pass_duration_mean',
    '__results_measurements_validateReleasePipelineRunCreation_pass_duration_mean',
    '__results_measurements_validateReleasePlanAdmission_pass_duration_mean',
    '__results_measurements_validateReleasePlan_pass_duration_mean',
    '__results_measurements_validateSnapshotCreation_pass_duration_mean',
    '__results_measurements_validateTestPipelineRunCondition_pass_duration_mean',
    '__results_measurements_validateTestPipelineRunCreation_pass_duration_mean',
  ], 's', 'Duration by test phase'),
  row.new('Error rate by test phase'),
  probes.durationsPanel(372, [
    '__results_measurements_HandleUser_error_rate',
    '__results_measurements_createApplication_error_rate',
    '__results_measurements_createComponent_error_rate',
    '__results_measurements_createIntegrationTestScenario_error_rate',
    '__results_measurements_createReleasePlanAdmission_error_rate',
    '__results_measurements_createReleasePlan_error_rate',
    '__results_measurements_getPaCPullNumber_error_rate',
    '__results_measurements_validateApplication_error_rate',
    '__results_measurements_validateComponentBuildSA_error_rate',  // TODO: Delme later, I was renamed to just __results_measurements_validateComponent_...
    '__results_measurements_validateComponent_error_rate',
    '__results_measurements_validateIntegrationTestScenario_error_rate',
    '__results_measurements_validatePipelineRunCondition_error_rate',
    '__results_measurements_validatePipelineRunCreation_error_rate',
    '__results_measurements_validatePipelineRunSignature_error_rate',
    '__results_measurements_validateReleaseCondition_error_rate',
    '__results_measurements_validateReleaseCreation_error_rate',
    '__results_measurements_validateReleasePipelineRunCondition_error_rate',
    '__results_measurements_validateReleasePipelineRunCreation_error_rate',
    '__results_measurements_validateReleasePlanAdmission_error_rate',
    '__results_measurements_validateReleasePlan_error_rate',
    '__results_measurements_validateSnapshotCreation_error_rate',
    '__results_measurements_validateTestPipelineRunCondition_error_rate',
    '__results_measurements_validateTestPipelineRunCreation_error_rate',
  ], 'none', 'Error rate by test phase', includePassingFilter=false),
  // Panels showing per task data
  row.new('Overall duration by task run'),
  probes.durationsPanel(372, [
    '__results_durations_stats_taskruns__build_apply_tags__passed_duration_mean',
    '__results_durations_stats_taskruns__build_buildah__passed_duration_mean',
    '__results_durations_stats_taskruns__build_build_image_index__passed_duration_mean',
    '__results_durations_stats_taskruns__build_clair_scan__passed_duration_mean',
    '__results_durations_stats_taskruns__build_clamav_scan__passed_duration_mean',
    '__results_durations_stats_taskruns__build_coverity_availability_check__passed_duration_mean',
    '__results_durations_stats_taskruns__build_deprecated_image_check__passed_duration_mean',
    '__results_durations_stats_taskruns__build_ecosystem_cert_preflight_checks__passed_duration_mean',
    '__results_durations_stats_taskruns__build_git_clone__passed_duration_mean',
    '__results_durations_stats_taskruns__build_init__passed_duration_mean',
    '__results_durations_stats_taskruns__build_push_dockerfile__passed_duration_mean',
    '__results_durations_stats_taskruns__build_rpms_signature_scan__passed_duration_mean',
    '__results_durations_stats_taskruns__build_sast_shell_check__passed_duration_mean',
    '__results_durations_stats_taskruns__build_sast_snyk_check__passed_duration_mean',
    '__results_durations_stats_taskruns__build_sast_unicode_check__passed_duration_mean',
    '__results_durations_stats_taskruns__build_show_sbom__passed_duration_mean',
    '__results_durations_stats_taskruns__build_summary__passed_duration_mean',
    '__results_durations_stats_taskruns__test_test_output__passed_duration_mean',
  ], 's', 'Overall duration by task run'),
  row.new('Running duration by task run'),
  probes.durationsPanel(372, [
    '__results_durations_stats_taskruns__build_apply_tags__passed_running_mean',
    '__results_durations_stats_taskruns__build_buildah__passed_running_mean',
    '__results_durations_stats_taskruns__build_build_image_index__passed_running_mean',
    '__results_durations_stats_taskruns__build_clair_scan__passed_running_mean',
    '__results_durations_stats_taskruns__build_clamav_scan__passed_running_mean',
    '__results_durations_stats_taskruns__build_coverity_availability_check__passed_running_mean',
    '__results_durations_stats_taskruns__build_deprecated_image_check__passed_running_mean',
    '__results_durations_stats_taskruns__build_ecosystem_cert_preflight_checks__passed_running_mean',
    '__results_durations_stats_taskruns__build_git_clone__passed_running_mean',
    '__results_durations_stats_taskruns__build_init__passed_running_mean',
    '__results_durations_stats_taskruns__build_push_dockerfile__passed_running_mean',
    '__results_durations_stats_taskruns__build_rpms_signature_scan__passed_running_mean',
    '__results_durations_stats_taskruns__build_sast_shell_check__passed_running_mean',
    '__results_durations_stats_taskruns__build_sast_snyk_check__passed_running_mean',
    '__results_durations_stats_taskruns__build_sast_unicode_check__passed_running_mean',
    '__results_durations_stats_taskruns__build_show_sbom__passed_running_mean',
    '__results_durations_stats_taskruns__build_summary__passed_running_mean',
    '__results_durations_stats_taskruns__test_test_output__passed_running_mean',
  ], 's', 'Running duration by task run'),
  row.new('Scheduled duration by task run'),
  probes.durationsPanel(372, [
    '__results_durations_stats_taskruns__build_apply_tags__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_buildah__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_build_image_index__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_clair_scan__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_clamav_scan__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_coverity_availability_check__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_deprecated_image_check__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_ecosystem_cert_preflight_checks__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_git_clone__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_init__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_push_dockerfile__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_rpms_signature_scan__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_sast_shell_check__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_sast_snyk_check__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_sast_unicode_check__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_show_sbom__passed_scheduled_mean',
    '__results_durations_stats_taskruns__build_summary__passed_scheduled_mean',
    '__results_durations_stats_taskruns__test_test_output__passed_scheduled_mean',
  ], 's', 'Scheduled duration by task run'),
  row.new('Idle duration by task run'),
  probes.durationsPanel(372, [
    '__results_durations_stats_taskruns__build_apply_tags__passed_idle_mean',
    '__results_durations_stats_taskruns__build_buildah__passed_idle_mean',
    '__results_durations_stats_taskruns__build_build_image_index__passed_idle_mean',
    '__results_durations_stats_taskruns__build_clair_scan__passed_idle_mean',
    '__results_durations_stats_taskruns__build_clamav_scan__passed_idle_mean',
    '__results_durations_stats_taskruns__build_coverity_availability_check__passed_idle_mean',
    '__results_durations_stats_taskruns__build_deprecated_image_check__passed_idle_mean',
    '__results_durations_stats_taskruns__build_ecosystem_cert_preflight_checks__passed_idle_mean',
    '__results_durations_stats_taskruns__build_git_clone__passed_idle_mean',
    '__results_durations_stats_taskruns__build_init__passed_idle_mean',
    '__results_durations_stats_taskruns__build_push_dockerfile__passed_idle_mean',
    '__results_durations_stats_taskruns__build_rpms_signature_scan__passed_idle_mean',
    '__results_durations_stats_taskruns__build_sast_shell_check__passed_idle_mean',
    '__results_durations_stats_taskruns__build_sast_snyk_check__passed_idle_mean',
    '__results_durations_stats_taskruns__build_sast_unicode_check__passed_idle_mean',
    '__results_durations_stats_taskruns__build_show_sbom__passed_idle_mean',
    '__results_durations_stats_taskruns__build_summary__passed_idle_mean',
    '__results_durations_stats_taskruns__test_test_output__passed_idle_mean',
  ], 's', 'Idle duration by task run'),
  row.new('Count of task runs'),
  probes.durationsPanel(372, [
    '__results_durations_stats_taskruns__build_apply_tags__passed_duration_samples',
    '__results_durations_stats_taskruns__build_buildah__passed_duration_samples',
    '__results_durations_stats_taskruns__build_build_image_index__passed_duration_samples',
    '__results_durations_stats_taskruns__build_clair_scan__passed_duration_samples',
    '__results_durations_stats_taskruns__build_clamav_scan__passed_duration_samples',
    '__results_durations_stats_taskruns__build_coverity_availability_check__passed_duration_samples',
    '__results_durations_stats_taskruns__build_deprecated_image_check__passed_duration_samples',
    '__results_durations_stats_taskruns__build_ecosystem_cert_preflight_checks__passed_duration_samples',
    '__results_durations_stats_taskruns__build_git_clone__passed_duration_samples',
    '__results_durations_stats_taskruns__build_init__passed_duration_samples',
    '__results_durations_stats_taskruns__build_push_dockerfile__passed_duration_samples',
    '__results_durations_stats_taskruns__build_rpms_signature_scan__passed_duration_samples',
    '__results_durations_stats_taskruns__build_sast_shell_check__passed_duration_samples',
    '__results_durations_stats_taskruns__build_sast_snyk_check__passed_duration_samples',
    '__results_durations_stats_taskruns__build_sast_unicode_check__passed_duration_samples',
    '__results_durations_stats_taskruns__build_show_sbom__passed_duration_samples',
    '__results_durations_stats_taskruns__build_summary__passed_duration_samples',
    '__results_durations_stats_taskruns__test_test_output__passed_duration_samples',
  ], 'none', 'Count of task runs'),
])
