{
 "title": "Performance: Controllers resources and restarts overview",
 "description": "Dashboard visualizes Konflux controllers basic resources use and health indicators: CPU, memory usage and number of restarts. Aim is to help spot unusual behavior.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Info about application-service / application-service-controller-manager-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU usage for application-service / application-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for application-service / application-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of application-service / application-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about build-service / build-service-controller-manager-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "CPU usage for build-service / build-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for build-service / build-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of build-service / build-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about image-controller / image-controller-controller-manager-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "CPU usage for image-controller / image-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for image-controller / image-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of image-controller / image-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about integration-service / integration-service-controller-manager-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "CPU usage for integration-service / integration-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for integration-service / integration-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of integration-service / integration-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about jvm-build-service / hacbs-jvm-operator-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "CPU usage for jvm-build-service / hacbs-jvm-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"jvm-build-service\",pod=~\"hacbs-jvm-operator-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"jvm-build-service\",pod=~\"hacbs-jvm-operator-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"jvm-build-service\",pod=~\"hacbs-jvm-operator-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"jvm-build-service\",pod=~\"hacbs-jvm-operator-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for jvm-build-service / hacbs-jvm-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"jvm-build-service\",pod=~\"hacbs-jvm-operator-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"jvm-build-service\",pod=~\"hacbs-jvm-operator-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"jvm-build-service\",pod=~\"hacbs-jvm-operator-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"jvm-build-service\",pod=~\"hacbs-jvm-operator-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of jvm-build-service / hacbs-jvm-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"jvm-build-service\",pod=~\"hacbs-jvm-operator-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about multi-platform-controller / multi-platform-controller-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }
  },
  {
   "title": "CPU usage for multi-platform-controller / multi-platform-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for multi-platform-controller / multi-platform-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of multi-platform-controller / multi-platform-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about multi-platform-controller / multi-platform-otp-server-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }
  },
  {
   "title": "CPU usage for multi-platform-controller / multi-platform-otp-server-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for multi-platform-controller / multi-platform-otp-server-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of multi-platform-controller / multi-platform-otp-server-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about notification-controller / notification-controller-controller-manager-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 }
  },
  {
   "title": "CPU usage for notification-controller / notification-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for notification-controller / notification-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of notification-controller / notification-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-etcd / etcd-ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.ec2.internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 }
  },
  {
   "title": "CPU usage for openshift-etcd / etcd-ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.ec2.internal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-etcd\",pod=~\"etcd-ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.ec2.internal\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-etcd\",pod=~\"etcd-ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.ec2.internal\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-etcd\",pod=~\"etcd-ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.ec2.internal\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-etcd\",pod=~\"etcd-ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.ec2.internal\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-etcd / etcd-ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.ec2.internal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-etcd\",pod=~\"etcd-ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.ec2.internal\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-etcd\",pod=~\"etcd-ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.ec2.internal\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-etcd\",pod=~\"etcd-ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.ec2.internal\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-etcd\",pod=~\"etcd-ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.ec2.internal\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-etcd / etcd-ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.ec2.internal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-etcd\",pod=~\"etcd-ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.ec2.internal\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-kube-apiserver / kube-apiserver-ip-.+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 }
  },
  {
   "title": "CPU usage for openshift-kube-apiserver / kube-apiserver-ip-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-kube-apiserver\",pod=~\"kube-apiserver-ip-.+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-kube-apiserver\",pod=~\"kube-apiserver-ip-.+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-kube-apiserver\",pod=~\"kube-apiserver-ip-.+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-kube-apiserver\",pod=~\"kube-apiserver-ip-.+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-kube-apiserver / kube-apiserver-ip-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-kube-apiserver\",pod=~\"kube-apiserver-ip-.+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-kube-apiserver\",pod=~\"kube-apiserver-ip-.+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-kube-apiserver\",pod=~\"kube-apiserver-ip-.+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-kube-apiserver\",pod=~\"kube-apiserver-ip-.+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-kube-apiserver / kube-apiserver-ip-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-kube-apiserver\",pod=~\"kube-apiserver-ip-.+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / pipeline-metrics-exporter-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 }
  },
  {
   "title": "CPU usage for openshift-pipelines / pipeline-metrics-exporter-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"pipeline-metrics-exporter-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"pipeline-metrics-exporter-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"pipeline-metrics-exporter-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"pipeline-metrics-exporter-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / pipeline-metrics-exporter-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"pipeline-metrics-exporter-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"pipeline-metrics-exporter-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"pipeline-metrics-exporter-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"pipeline-metrics-exporter-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / pipeline-metrics-exporter-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"pipeline-metrics-exporter-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / pipelines-as-code-controller-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 }
  },
  {
   "title": "CPU usage for openshift-pipelines / pipelines-as-code-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-controller-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-controller-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / pipelines-as-code-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-controller-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-controller-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / pipelines-as-code-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-controller-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / pipelines-as-code-watcher-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 }
  },
  {
   "title": "CPU usage for openshift-pipelines / pipelines-as-code-watcher-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-watcher-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-watcher-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-watcher-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-watcher-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / pipelines-as-code-watcher-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-watcher-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-watcher-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-watcher-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-watcher-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / pipelines-as-code-watcher-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-watcher-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / pipelines-as-code-webhook-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 }
  },
  {
   "title": "CPU usage for openshift-pipelines / pipelines-as-code-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-webhook-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-webhook-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / pipelines-as-code-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-webhook-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-webhook-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / pipelines-as-code-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"pipelines-as-code-webhook-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / pipelines-console-plugin-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 }
  },
  {
   "title": "CPU usage for openshift-pipelines / pipelines-console-plugin-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"pipelines-console-plugin-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"pipelines-console-plugin-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"pipelines-console-plugin-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"pipelines-console-plugin-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / pipelines-console-plugin-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"pipelines-console-plugin-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"pipelines-console-plugin-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"pipelines-console-plugin-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"pipelines-console-plugin-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / pipelines-console-plugin-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"pipelines-console-plugin-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / tekton-chains-controller-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 }
  },
  {
   "title": "CPU usage for openshift-pipelines / tekton-chains-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-chains-controller-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-chains-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-chains-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-chains-controller-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / tekton-chains-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-chains-controller-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-chains-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-chains-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-chains-controller-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / tekton-chains-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"tekton-chains-controller-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / tekton-events-controller-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 }
  },
  {
   "title": "CPU usage for openshift-pipelines / tekton-events-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-events-controller-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-events-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-events-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-events-controller-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / tekton-events-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-events-controller-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-events-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-events-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-events-controller-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / tekton-events-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"tekton-events-controller-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / tekton-operator-proxy-webhook-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 }
  },
  {
   "title": "CPU usage for openshift-pipelines / tekton-operator-proxy-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-operator-proxy-webhook-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-operator-proxy-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-operator-proxy-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-operator-proxy-webhook-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / tekton-operator-proxy-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-operator-proxy-webhook-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-operator-proxy-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-operator-proxy-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-operator-proxy-webhook-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / tekton-operator-proxy-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"tekton-operator-proxy-webhook-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / tekton-pipelines-controller-[0-9]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 }
  },
  {
   "title": "CPU usage for openshift-pipelines / tekton-pipelines-controller-[0-9]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-controller-[0-9]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-controller-[0-9]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-controller-[0-9]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-controller-[0-9]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / tekton-pipelines-controller-[0-9]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-controller-[0-9]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-controller-[0-9]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-controller-[0-9]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-controller-[0-9]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / tekton-pipelines-controller-[0-9]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-controller-[0-9]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / tekton-pipelines-remote-resolvers-[0-9]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 }
  },
  {
   "title": "CPU usage for openshift-pipelines / tekton-pipelines-remote-resolvers-[0-9]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-remote-resolvers-[0-9]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-remote-resolvers-[0-9]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-remote-resolvers-[0-9]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-remote-resolvers-[0-9]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / tekton-pipelines-remote-resolvers-[0-9]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-remote-resolvers-[0-9]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-remote-resolvers-[0-9]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-remote-resolvers-[0-9]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-remote-resolvers-[0-9]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / tekton-pipelines-remote-resolvers-[0-9]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"tekton-pipelines-remote-resolvers-[0-9]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / tekton-triggers-controller-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 }
  },
  {
   "title": "CPU usage for openshift-pipelines / tekton-triggers-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-controller-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-controller-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / tekton-triggers-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-controller-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-controller-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / tekton-triggers-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-controller-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / tekton-triggers-core-interceptors-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 }
  },
  {
   "title": "CPU usage for openshift-pipelines / tekton-triggers-core-interceptors-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-core-interceptors-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-core-interceptors-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-core-interceptors-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-core-interceptors-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / tekton-triggers-core-interceptors-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-core-interceptors-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-core-interceptors-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-core-interceptors-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-core-interceptors-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / tekton-triggers-core-interceptors-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-core-interceptors-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / tekton-triggers-webhook-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 }
  },
  {
   "title": "CPU usage for openshift-pipelines / tekton-triggers-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-webhook-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-webhook-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / tekton-triggers-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-webhook-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-webhook-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / tekton-triggers-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"tekton-triggers-webhook-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about openshift-pipelines / tkn-cli-serve-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 207 }
  },
  {
   "title": "CPU usage for openshift-pipelines / tkn-cli-serve-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tkn-cli-serve-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tkn-cli-serve-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"openshift-pipelines\",pod=~\"tkn-cli-serve-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"openshift-pipelines\",pod=~\"tkn-cli-serve-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for openshift-pipelines / tkn-cli-serve-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tkn-cli-serve-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tkn-cli-serve-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"openshift-pipelines\",pod=~\"tkn-cli-serve-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"openshift-pipelines\",pod=~\"tkn-cli-serve-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of openshift-pipelines / tkn-cli-serve-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"openshift-pipelines\",pod=~\"tkn-cli-serve-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about project-controller / project-controller-controller-manager-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 216 }
  },
  {
   "title": "CPU usage for project-controller / project-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"project-controller\",pod=~\"project-controller-controller-manager-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"project-controller\",pod=~\"project-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"project-controller\",pod=~\"project-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"project-controller\",pod=~\"project-controller-controller-manager-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for project-controller / project-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"project-controller\",pod=~\"project-controller-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"project-controller\",pod=~\"project-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"project-controller\",pod=~\"project-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"project-controller\",pod=~\"project-controller-controller-manager-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of project-controller / project-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"project-controller\",pod=~\"project-controller-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about release-service / release-service-controller-manager-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 225 }
  },
  {
   "title": "CPU usage for release-service / release-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"release-service\",pod=~\"release-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"release-service\",pod=~\"release-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"release-service\",pod=~\"release-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"release-service\",pod=~\"release-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for release-service / release-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"release-service\",pod=~\"release-service-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"release-service\",pod=~\"release-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"release-service\",pod=~\"release-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"release-service\",pod=~\"release-service-controller-manager-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of release-service / release-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"release-service\",pod=~\"release-service-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about release-service / release-service-monitor-deployment-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 }
  },
  {
   "title": "CPU usage for release-service / release-service-monitor-deployment-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"release-service\",pod=~\"release-service-monitor-deployment-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"release-service\",pod=~\"release-service-monitor-deployment-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"release-service\",pod=~\"release-service-monitor-deployment-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"release-service\",pod=~\"release-service-monitor-deployment-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for release-service / release-service-monitor-deployment-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"release-service\",pod=~\"release-service-monitor-deployment-[0-9a-z-]+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"release-service\",pod=~\"release-service-monitor-deployment-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"release-service\",pod=~\"release-service-monitor-deployment-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"release-service\",pod=~\"release-service-monitor-deployment-[0-9a-z-]+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of release-service / release-service-monitor-deployment-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"release-service\",pod=~\"release-service-monitor-deployment-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about tekton-logging / vector-tekton-logs-collector-.+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 243 }
  },
  {
   "title": "CPU usage for tekton-logging / vector-tekton-logs-collector-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"tekton-logging\",pod=~\"vector-tekton-logs-collector-.+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"tekton-logging\",pod=~\"vector-tekton-logs-collector-.+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"tekton-logging\",pod=~\"vector-tekton-logs-collector-.+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"tekton-logging\",pod=~\"vector-tekton-logs-collector-.+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for tekton-logging / vector-tekton-logs-collector-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"tekton-logging\",pod=~\"vector-tekton-logs-collector-.+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"tekton-logging\",pod=~\"vector-tekton-logs-collector-.+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"tekton-logging\",pod=~\"vector-tekton-logs-collector-.+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"tekton-logging\",pod=~\"vector-tekton-logs-collector-.+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of tekton-logging / vector-tekton-logs-collector-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"tekton-logging\",pod=~\"vector-tekton-logs-collector-.+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about tekton-results / tekton-results-api-.+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 252 }
  },
  {
   "title": "CPU usage for tekton-results / tekton-results-api-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"tekton-results\",pod=~\"tekton-results-api-.+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"tekton-results\",pod=~\"tekton-results-api-.+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"tekton-results\",pod=~\"tekton-results-api-.+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"tekton-results\",pod=~\"tekton-results-api-.+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for tekton-results / tekton-results-api-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"tekton-results\",pod=~\"tekton-results-api-.+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"tekton-results\",pod=~\"tekton-results-api-.+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"tekton-results\",pod=~\"tekton-results-api-.+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"tekton-results\",pod=~\"tekton-results-api-.+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of tekton-results / tekton-results-api-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"tekton-results\",pod=~\"tekton-results-api-.+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about tekton-results / tekton-results-api-for-watcher-.+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 261 }
  },
  {
   "title": "CPU usage for tekton-results / tekton-results-api-for-watcher-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"tekton-results\",pod=~\"tekton-results-api-for-watcher-.+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"tekton-results\",pod=~\"tekton-results-api-for-watcher-.+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"tekton-results\",pod=~\"tekton-results-api-for-watcher-.+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"tekton-results\",pod=~\"tekton-results-api-for-watcher-.+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for tekton-results / tekton-results-api-for-watcher-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"tekton-results\",pod=~\"tekton-results-api-for-watcher-.+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"tekton-results\",pod=~\"tekton-results-api-for-watcher-.+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"tekton-results\",pod=~\"tekton-results-api-for-watcher-.+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"tekton-results\",pod=~\"tekton-results-api-for-watcher-.+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of tekton-results / tekton-results-api-for-watcher-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"tekton-results\",pod=~\"tekton-results-api-for-watcher-.+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about tekton-results / tekton-results-watcher-.+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 270 }
  },
  {
   "title": "CPU usage for tekton-results / tekton-results-watcher-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"tekton-results\",pod=~\"tekton-results-watcher-.+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"tekton-results\",pod=~\"tekton-results-watcher-.+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"tekton-results\",pod=~\"tekton-results-watcher-.+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"tekton-results\",pod=~\"tekton-results-watcher-.+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for tekton-results / tekton-results-watcher-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"tekton-results\",pod=~\"tekton-results-watcher-.+\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"tekton-results\",pod=~\"tekton-results-watcher-.+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"tekton-results\",pod=~\"tekton-results-watcher-.+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"tekton-results\",pod=~\"tekton-results-watcher-.+\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of tekton-results / tekton-results-watcher-.+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"tekton-results\",pod=~\"tekton-results-watcher-.+\"})",
     "legendFormat": "restarts"
    }
   ]
  }
 ]
}