{
 "title": "Performance: Controllers resources and restarts overview (namespaces starting with a - n)",
 "description": "Dashboard visualizes Konflux controllers basic resources use and health indicators: CPU, memory usage and number of restarts. Aim is to help spot unusual behavior.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Info about application-service / application-service-controller-manager-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU usage for application-service / application-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for application-service / application-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of application-service / application-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"application-service\",pod=~\"application-service-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about appstudio-grafana / grafana-operator-controller-manager-v5-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "CPU usage for appstudio-grafana / grafana-operator-controller-manager-v5-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"appstudio-grafana\",pod=~\"grafana-operator-controller-manager-v5-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"appstudio-grafana\",pod=~\"grafana-operator-controller-manager-v5-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"appstudio-grafana\",pod=~\"grafana-operator-controller-manager-v5-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"appstudio-grafana\",pod=~\"grafana-operator-controller-manager-v5-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for appstudio-grafana / grafana-operator-controller-manager-v5-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"appstudio-grafana\",pod=~\"grafana-operator-controller-manager-v5-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"appstudio-grafana\",pod=~\"grafana-operator-controller-manager-v5-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"appstudio-grafana\",pod=~\"grafana-operator-controller-manager-v5-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"appstudio-grafana\",pod=~\"grafana-operator-controller-manager-v5-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of appstudio-grafana / grafana-operator-controller-manager-v5-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"appstudio-grafana\",pod=~\"grafana-operator-controller-manager-v5-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about appstudio-monitoring / obo-prometheus-operator-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "CPU usage for appstudio-monitoring / obo-prometheus-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"appstudio-monitoring\",pod=~\"obo-prometheus-operator-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"appstudio-monitoring\",pod=~\"obo-prometheus-operator-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"appstudio-monitoring\",pod=~\"obo-prometheus-operator-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"appstudio-monitoring\",pod=~\"obo-prometheus-operator-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for appstudio-monitoring / obo-prometheus-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"appstudio-monitoring\",pod=~\"obo-prometheus-operator-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"appstudio-monitoring\",pod=~\"obo-prometheus-operator-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"appstudio-monitoring\",pod=~\"obo-prometheus-operator-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"appstudio-monitoring\",pod=~\"obo-prometheus-operator-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of appstudio-monitoring / obo-prometheus-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"appstudio-monitoring\",pod=~\"obo-prometheus-operator-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about appstudio-monitoring / observability-operator-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "CPU usage for appstudio-monitoring / observability-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"appstudio-monitoring\",pod=~\"observability-operator-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"appstudio-monitoring\",pod=~\"observability-operator-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"appstudio-monitoring\",pod=~\"observability-operator-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"appstudio-monitoring\",pod=~\"observability-operator-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for appstudio-monitoring / observability-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"appstudio-monitoring\",pod=~\"observability-operator-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"appstudio-monitoring\",pod=~\"observability-operator-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"appstudio-monitoring\",pod=~\"observability-operator-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"appstudio-monitoring\",pod=~\"observability-operator-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of appstudio-monitoring / observability-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"appstudio-monitoring\",pod=~\"observability-operator-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about appstudio-monitoring / perses-operator-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "CPU usage for appstudio-monitoring / perses-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"appstudio-monitoring\",pod=~\"perses-operator-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"appstudio-monitoring\",pod=~\"perses-operator-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"appstudio-monitoring\",pod=~\"perses-operator-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"appstudio-monitoring\",pod=~\"perses-operator-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for appstudio-monitoring / perses-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"appstudio-monitoring\",pod=~\"perses-operator-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"appstudio-monitoring\",pod=~\"perses-operator-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"appstudio-monitoring\",pod=~\"perses-operator-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"appstudio-monitoring\",pod=~\"perses-operator-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of appstudio-monitoring / perses-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"appstudio-monitoring\",pod=~\"perses-operator-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about build-service / build-service-controller-manager-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }
  },
  {
   "title": "CPU usage for build-service / build-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for build-service / build-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of build-service / build-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"build-service\",pod=~\"build-service-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about etcd-shield / etcd-shield-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }
  },
  {
   "title": "CPU usage for etcd-shield / etcd-shield-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"etcd-shield\",pod=~\"etcd-shield-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"etcd-shield\",pod=~\"etcd-shield-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"etcd-shield\",pod=~\"etcd-shield-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"etcd-shield\",pod=~\"etcd-shield-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for etcd-shield / etcd-shield-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"etcd-shield\",pod=~\"etcd-shield-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"etcd-shield\",pod=~\"etcd-shield-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"etcd-shield\",pod=~\"etcd-shield-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"etcd-shield\",pod=~\"etcd-shield-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of etcd-shield / etcd-shield-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"etcd-shield\",pod=~\"etcd-shield-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about external-secrets-operator / external-secrets-operator-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 }
  },
  {
   "title": "CPU usage for external-secrets-operator / external-secrets-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for external-secrets-operator / external-secrets-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of external-secrets-operator / external-secrets-operator-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about external-secrets-operator / external-secrets-operator-cert-controller-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 }
  },
  {
   "title": "CPU usage for external-secrets-operator / external-secrets-operator-cert-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-cert-controller-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-cert-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-cert-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-cert-controller-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for external-secrets-operator / external-secrets-operator-cert-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-cert-controller-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-cert-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-cert-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-cert-controller-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of external-secrets-operator / external-secrets-operator-cert-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-cert-controller-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about external-secrets-operator / external-secrets-operator-webhook-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 }
  },
  {
   "title": "CPU usage for external-secrets-operator / external-secrets-operator-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-webhook-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-webhook-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for external-secrets-operator / external-secrets-operator-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-webhook-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-webhook-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of external-secrets-operator / external-secrets-operator-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"external-secrets-operator\",pod=~\"external-secrets-operator-webhook-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about image-controller / image-controller-controller-manager-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 }
  },
  {
   "title": "CPU usage for image-controller / image-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for image-controller / image-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of image-controller / image-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"image-controller\",pod=~\"image-controller-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about image-rbac-proxy / dex-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 }
  },
  {
   "title": "CPU usage for image-rbac-proxy / dex-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"image-rbac-proxy\",pod=~\"dex-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"image-rbac-proxy\",pod=~\"dex-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"image-rbac-proxy\",pod=~\"dex-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"image-rbac-proxy\",pod=~\"dex-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for image-rbac-proxy / dex-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"image-rbac-proxy\",pod=~\"dex-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"image-rbac-proxy\",pod=~\"dex-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"image-rbac-proxy\",pod=~\"dex-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"image-rbac-proxy\",pod=~\"dex-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of image-rbac-proxy / dex-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"image-rbac-proxy\",pod=~\"dex-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about image-rbac-proxy / image-rbac-proxy-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 }
  },
  {
   "title": "CPU usage for image-rbac-proxy / image-rbac-proxy-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"image-rbac-proxy\",pod=~\"image-rbac-proxy-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"image-rbac-proxy\",pod=~\"image-rbac-proxy-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"image-rbac-proxy\",pod=~\"image-rbac-proxy-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"image-rbac-proxy\",pod=~\"image-rbac-proxy-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for image-rbac-proxy / image-rbac-proxy-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"image-rbac-proxy\",pod=~\"image-rbac-proxy-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"image-rbac-proxy\",pod=~\"image-rbac-proxy-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"image-rbac-proxy\",pod=~\"image-rbac-proxy-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"image-rbac-proxy\",pod=~\"image-rbac-proxy-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of image-rbac-proxy / image-rbac-proxy-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"image-rbac-proxy\",pod=~\"image-rbac-proxy-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about integration-service / integration-service-controller-manager-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 }
  },
  {
   "title": "CPU usage for integration-service / integration-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for integration-service / integration-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of integration-service / integration-service-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"integration-service\",pod=~\"integration-service-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about knative-eventing / eventing-controller-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 }
  },
  {
   "title": "CPU usage for knative-eventing / eventing-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"eventing-controller-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"eventing-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"eventing-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"eventing-controller-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for knative-eventing / eventing-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"eventing-controller-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"eventing-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"eventing-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"eventing-controller-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of knative-eventing / eventing-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"knative-eventing\",pod=~\"eventing-controller-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about knative-eventing / eventing-webhook-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 }
  },
  {
   "title": "CPU usage for knative-eventing / eventing-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"eventing-webhook-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"eventing-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"eventing-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"eventing-webhook-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for knative-eventing / eventing-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"eventing-webhook-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"eventing-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"eventing-webhook-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"eventing-webhook-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of knative-eventing / eventing-webhook-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"knative-eventing\",pod=~\"eventing-webhook-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about knative-eventing / imc-controller-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 }
  },
  {
   "title": "CPU usage for knative-eventing / imc-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"imc-controller-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"imc-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"imc-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"imc-controller-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for knative-eventing / imc-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"imc-controller-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"imc-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"imc-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"imc-controller-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of knative-eventing / imc-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"knative-eventing\",pod=~\"imc-controller-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about knative-eventing / imc-dispatcher-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 }
  },
  {
   "title": "CPU usage for knative-eventing / imc-dispatcher-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"imc-dispatcher-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"imc-dispatcher-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"imc-dispatcher-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"imc-dispatcher-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for knative-eventing / imc-dispatcher-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"imc-dispatcher-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"imc-dispatcher-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"imc-dispatcher-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"imc-dispatcher-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of knative-eventing / imc-dispatcher-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"knative-eventing\",pod=~\"imc-dispatcher-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about knative-eventing / job-sink-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 }
  },
  {
   "title": "CPU usage for knative-eventing / job-sink-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"job-sink-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"job-sink-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"job-sink-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"job-sink-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for knative-eventing / job-sink-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"job-sink-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"job-sink-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"job-sink-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"job-sink-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of knative-eventing / job-sink-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"knative-eventing\",pod=~\"job-sink-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about knative-eventing / mt-broker-controller-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 }
  },
  {
   "title": "CPU usage for knative-eventing / mt-broker-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"mt-broker-controller-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"mt-broker-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"mt-broker-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"mt-broker-controller-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for knative-eventing / mt-broker-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"mt-broker-controller-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"mt-broker-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"mt-broker-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"mt-broker-controller-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of knative-eventing / mt-broker-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"knative-eventing\",pod=~\"mt-broker-controller-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about knative-eventing / mt-broker-filter-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 }
  },
  {
   "title": "CPU usage for knative-eventing / mt-broker-filter-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"mt-broker-filter-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"mt-broker-filter-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"mt-broker-filter-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"mt-broker-filter-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for knative-eventing / mt-broker-filter-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"mt-broker-filter-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"mt-broker-filter-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"mt-broker-filter-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"mt-broker-filter-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of knative-eventing / mt-broker-filter-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"knative-eventing\",pod=~\"mt-broker-filter-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about knative-eventing / mt-broker-ingress-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 }
  },
  {
   "title": "CPU usage for knative-eventing / mt-broker-ingress-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"mt-broker-ingress-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"mt-broker-ingress-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"knative-eventing\",pod=~\"mt-broker-ingress-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"knative-eventing\",pod=~\"mt-broker-ingress-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for knative-eventing / mt-broker-ingress-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"mt-broker-ingress-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"mt-broker-ingress-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"knative-eventing\",pod=~\"mt-broker-ingress-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"knative-eventing\",pod=~\"mt-broker-ingress-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of knative-eventing / mt-broker-ingress-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"knative-eventing\",pod=~\"mt-broker-ingress-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about konflux-kite / konflux-kite-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 }
  },
  {
   "title": "CPU usage for konflux-kite / konflux-kite-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"konflux-kite\",pod=~\"konflux-kite-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"konflux-kite\",pod=~\"konflux-kite-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"konflux-kite\",pod=~\"konflux-kite-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"konflux-kite\",pod=~\"konflux-kite-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for konflux-kite / konflux-kite-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-kite\",pod=~\"konflux-kite-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"konflux-kite\",pod=~\"konflux-kite-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"konflux-kite\",pod=~\"konflux-kite-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-kite\",pod=~\"konflux-kite-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of konflux-kite / konflux-kite-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"konflux-kite\",pod=~\"konflux-kite-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about konflux-kyverno / kyverno-admission-controller-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 207 }
  },
  {
   "title": "CPU usage for konflux-kyverno / kyverno-admission-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"konflux-kyverno\",pod=~\"kyverno-admission-controller-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"konflux-kyverno\",pod=~\"kyverno-admission-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"konflux-kyverno\",pod=~\"kyverno-admission-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"konflux-kyverno\",pod=~\"kyverno-admission-controller-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for konflux-kyverno / kyverno-admission-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-kyverno\",pod=~\"kyverno-admission-controller-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"konflux-kyverno\",pod=~\"kyverno-admission-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"konflux-kyverno\",pod=~\"kyverno-admission-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-kyverno\",pod=~\"kyverno-admission-controller-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of konflux-kyverno / kyverno-admission-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"konflux-kyverno\",pod=~\"kyverno-admission-controller-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about konflux-kyverno / kyverno-background-controller-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 216 }
  },
  {
   "title": "CPU usage for konflux-kyverno / kyverno-background-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"konflux-kyverno\",pod=~\"kyverno-background-controller-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"konflux-kyverno\",pod=~\"kyverno-background-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"konflux-kyverno\",pod=~\"kyverno-background-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"konflux-kyverno\",pod=~\"kyverno-background-controller-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for konflux-kyverno / kyverno-background-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-kyverno\",pod=~\"kyverno-background-controller-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"konflux-kyverno\",pod=~\"kyverno-background-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"konflux-kyverno\",pod=~\"kyverno-background-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-kyverno\",pod=~\"kyverno-background-controller-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of konflux-kyverno / kyverno-background-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"konflux-kyverno\",pod=~\"kyverno-background-controller-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about konflux-kyverno / kyverno-cleanup-controller-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 225 }
  },
  {
   "title": "CPU usage for konflux-kyverno / kyverno-cleanup-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"konflux-kyverno\",pod=~\"kyverno-cleanup-controller-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"konflux-kyverno\",pod=~\"kyverno-cleanup-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"konflux-kyverno\",pod=~\"kyverno-cleanup-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"konflux-kyverno\",pod=~\"kyverno-cleanup-controller-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for konflux-kyverno / kyverno-cleanup-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-kyverno\",pod=~\"kyverno-cleanup-controller-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"konflux-kyverno\",pod=~\"kyverno-cleanup-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"konflux-kyverno\",pod=~\"kyverno-cleanup-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-kyverno\",pod=~\"kyverno-cleanup-controller-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of konflux-kyverno / kyverno-cleanup-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"konflux-kyverno\",pod=~\"kyverno-cleanup-controller-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about konflux-otel / open-telemetry-opentelemetry-collector-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 }
  },
  {
   "title": "CPU usage for konflux-otel / open-telemetry-opentelemetry-collector-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"konflux-otel\",pod=~\"open-telemetry-opentelemetry-collector-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"konflux-otel\",pod=~\"open-telemetry-opentelemetry-collector-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"konflux-otel\",pod=~\"open-telemetry-opentelemetry-collector-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"konflux-otel\",pod=~\"open-telemetry-opentelemetry-collector-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for konflux-otel / open-telemetry-opentelemetry-collector-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-otel\",pod=~\"open-telemetry-opentelemetry-collector-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"konflux-otel\",pod=~\"open-telemetry-opentelemetry-collector-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"konflux-otel\",pod=~\"open-telemetry-opentelemetry-collector-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-otel\",pod=~\"open-telemetry-opentelemetry-collector-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of konflux-otel / open-telemetry-opentelemetry-collector-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"konflux-otel\",pod=~\"open-telemetry-opentelemetry-collector-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about konflux-ui / dex-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 243 }
  },
  {
   "title": "CPU usage for konflux-ui / dex-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"konflux-ui\",pod=~\"dex-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"konflux-ui\",pod=~\"dex-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"konflux-ui\",pod=~\"dex-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"konflux-ui\",pod=~\"dex-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for konflux-ui / dex-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-ui\",pod=~\"dex-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"konflux-ui\",pod=~\"dex-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"konflux-ui\",pod=~\"dex-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-ui\",pod=~\"dex-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of konflux-ui / dex-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"konflux-ui\",pod=~\"dex-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about konflux-ui / proxy-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 252 }
  },
  {
   "title": "CPU usage for konflux-ui / proxy-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"konflux-ui\",pod=~\"proxy-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"konflux-ui\",pod=~\"proxy-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"konflux-ui\",pod=~\"proxy-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"konflux-ui\",pod=~\"proxy-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for konflux-ui / proxy-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-ui\",pod=~\"proxy-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"konflux-ui\",pod=~\"proxy-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"konflux-ui\",pod=~\"proxy-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"konflux-ui\",pod=~\"proxy-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of konflux-ui / proxy-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"konflux-ui\",pod=~\"proxy-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about mintmaker / mintmaker-controller-manager-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 261 }
  },
  {
   "title": "CPU usage for mintmaker / mintmaker-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"mintmaker\",pod=~\"mintmaker-controller-manager-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"mintmaker\",pod=~\"mintmaker-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"mintmaker\",pod=~\"mintmaker-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"mintmaker\",pod=~\"mintmaker-controller-manager-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for mintmaker / mintmaker-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"mintmaker\",pod=~\"mintmaker-controller-manager-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"mintmaker\",pod=~\"mintmaker-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"mintmaker\",pod=~\"mintmaker-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"mintmaker\",pod=~\"mintmaker-controller-manager-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of mintmaker / mintmaker-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"mintmaker\",pod=~\"mintmaker-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about multi-platform-controller / multi-platform-controller-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 270 }
  },
  {
   "title": "CPU usage for multi-platform-controller / multi-platform-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for multi-platform-controller / multi-platform-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of multi-platform-controller / multi-platform-controller-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"multi-platform-controller\",pod=~\"multi-platform-controller-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about multi-platform-controller / multi-platform-otp-server-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 279 }
  },
  {
   "title": "CPU usage for multi-platform-controller / multi-platform-otp-server-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 280 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for multi-platform-controller / multi-platform-otp-server-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 280 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of multi-platform-controller / multi-platform-otp-server-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 280 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"multi-platform-controller\",pod=~\"multi-platform-otp-server-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about namespace-lister / namespace-lister-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 288 }
  },
  {
   "title": "CPU usage for namespace-lister / namespace-lister-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"namespace-lister\",pod=~\"namespace-lister-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"namespace-lister\",pod=~\"namespace-lister-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"namespace-lister\",pod=~\"namespace-lister-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"namespace-lister\",pod=~\"namespace-lister-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for namespace-lister / namespace-lister-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"namespace-lister\",pod=~\"namespace-lister-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"namespace-lister\",pod=~\"namespace-lister-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"namespace-lister\",pod=~\"namespace-lister-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"namespace-lister\",pod=~\"namespace-lister-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of namespace-lister / namespace-lister-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"namespace-lister\",pod=~\"namespace-lister-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Info about notification-controller / notification-controller-controller-manager-[0-9a-z-]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 297 }
  },
  {
   "title": "CPU usage for notification-controller / notification-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "sum by (pod) (avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(sum by (pod) (avg(rate(container_cpu_usage_seconds_total{namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"}[$__rate_interval])))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Mem usage for notification-controller / notification-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\",container=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\",namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "REQUESTS"
    },
    {
     "expr": "avg(sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\",namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"}))",
     "legendFormat": "LIMITS"
    },
    {
     "expr": "avg_over_time(avg(sum by (pod) (container_memory_working_set_bytes{namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\",container=\"\"}))[24h:])",
     "legendFormat": "24h AVG"
    }
   ]
  },
  {
   "title": "Restarts of notification-controller / notification-controller-controller-manager-[0-9a-z-]+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"notification-controller\",pod=~\"notification-controller-controller-manager-[0-9a-z-]+\"})",
     "legendFormat": "restarts"
    }
   ]
  }
 ]
}