{
 "title": "Performance: Debugging customer issues",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Overal PipelineRun load on the cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Existing PipelineRun and TaskRun count by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tekton_pipelines_controller_pipelinerun_count[60m])) by (status)",
     "legendFormat": "{{status}} PipelineRun count"
    },
    {
     "expr": "sum(rate(tekton_pipelines_controller_taskrun_count[60m])) by (status)",
     "legendFormat": "{{status}} TaskRun count"
    }
   ]
  },
  {
   "title": "Running PipelineRuns and TaskRuns count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(tekton_pipelines_controller_running_pipelineruns_count)",
     "legendFormat": "Running PipelineRuns count"
    },
    {
     "expr": "avg(tekton_pipelines_controller_running_taskruns_count)",
     "legendFormat": "Running TaskRuns count"
    }
   ]
  },
  { "title": "Issues on the cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Count of throttled TaskRuns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(tekton_pipelines_controller_running_taskruns_throttled_by_quota_count)",
     "legendFormat": "by quota"
    },
    {
     "expr": "avg(tekton_pipelines_controller_running_taskruns_throttled_by_node_count)",
     "legendFormat": "by node"
    }
   ]
  },
  {
   "title": "Pipelines controller work queue depth by Reconciler",
   "type": "timeseries",
   "description": "Normally should be close to zero, above 1k means Pipelines controller is lagging a lot and you might want to ensure if all replicas are doing their part.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_work_queue_depth",
     "legendFormat": "{{reconciler}}"
    }
   ]
  },
  {
   "title": "Number of TaskRuns that do not have it's Pod yet",
   "type": "timeseries",
   "description": "This should be 0 all the time, anything above 0 means Pipelines controller is lagging a lot and you might want to ensure if all replicas are doing their part.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(taskrun_pod_create_not_attempted_or_pending_count)",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Autoscaler scale-ups and -downs",
   "type": "timeseries",
   "description": "Number of cluster autoscaler scale-up and -down events in last hour.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(cluster_autoscaler_scaled_up_nodes_total[1h]) * 3600",
     "legendFormat": "Scale ups"
    },
    {
     "expr": "rate(cluster_autoscaler_scaled_down_nodes_total[1h]) * 3600",
     "legendFormat": "Scale downs"
    }
   ]
  },
  {
   "title": "K8s scheduler pending Pods per queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(scheduler_pending_pods) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "PVCs status by phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pipelines controller replicas CPU Usage",
   "type": "timeseries",
   "description": "If some of the replicas is working far more than the other, maybe leases are not distributed correctly. See leases distribution graph.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"tekton-pipelines-controller-.*\", namespace=\"openshift-pipelines\", container=\"\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pipelines controller replicas memory utilization",
   "type": "timeseries",
   "description": "If some of the replicas is consuming far more than the other, maybe leases are not distributed correctly. See leases distribution graph.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"tekton-pipelines-controller-.*\", namespace=\"openshift-pipelines\", container=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pipelines Controller leases distribution",
   "type": "timeseries",
   "description": "In each bucket, we have 8 leases. These leases should be distributed over more than 1 Pipelines controller replicas pods. If they are not, we might need Infra team intervention.\n\nDashed lines shows \"health\" intervals: if it is 0 or 1, call Infra team (we have alert for that); if it is 2, it is not giving good performance; 3 or 4 should be OK even during peaks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by (lease_holder) (kube_lease_owner{lease=~\"tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.reconciler..*\", lease_holder!=\"\"}))",
     "legendFormat": "PipelineRun reconciler"
    },
    {
     "expr": "count(count by (lease_holder) (kube_lease_owner{lease=~\"tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.taskrun.reconciler..*\", lease_holder!=\"\"}))",
     "legendFormat": "TaskRun reconciler"
    },
    {
     "expr": "count(count by (lease_holder) (kube_lease_owner{lease=~\"tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.resolutionrequest.reconciler..*\", lease_holder!=\"\"}))",
     "legendFormat": "ResolutionRequest reconciler"
    }
   ]
  },
  { "title": "Most active tenants", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "PipelineRun duration rate by Namespace",
   "type": "timeseries",
   "description": "Unit here is duration burned by PipelineRuns in given Namespace in last hour",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "topk(3, sum(rate(tekton_pipelines_controller_pipelinerun_duration_seconds_sum[60m])) by (namespace)) * 3600",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "PipelineRun count rate by Namespace",
   "type": "timeseries",
   "description": "Unit here is number of finished PipelineRuns in given Namespace in last hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(3, sum(rate(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds_count[60m])) by (namespace)) * 3600",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}