{
 "title": "Performance: Worker nodes utilization",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage percentage per worker node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)\nand on (instance)\n  label_replace(\n    kube_node_role{role=\"worker\"} unless on (node) kube_node_role{role=\"infra\"},\n    \"instance\", \"$1\", \"node\", \"(.+)\"\n  )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage in percentage per worker node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  avg_over_time(node_memory_MemAvailable_bytes[10m]) * 100\n  /\n  avg_over_time(node_memory_MemTotal_bytes[10m])\n)\nand on (instance)\n  label_replace(kube_node_role{role=\"worker\"} unless on (node) kube_node_role\n{role=\"infra\"}, \"instance\", \"$1\", \"node\", \"(.+)\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk read+write bytes per second averaged over 1 hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(node_disk_read_bytes_total[1h])\n  +\n  rate(node_disk_written_bytes_total[1h])\n) by (instance)\nand on (instance)\n  label_replace(\n    kube_node_role{role=\"worker\"} unless on (node) kube_node_role{role=\"infra\"},\n    \"instance\", \"$1\", \"node\", \"(.+)\"\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network received and transmitted bytes per second averaged over 1 hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(node_network_receive_bytes_total[1h])\n  +\n  rate(node_network_transmit_bytes_total[1h])\n) by (instance)\nand on (instance)\n  label_replace(\n    kube_node_role{role=\"worker\"} unless on (node) kube_node_role{role=\"infra\"},\n    \"instance\", \"$1\", \"node\", \"(.+)\"\n  )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}