{
 "title": "Pods performance",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace regexp", "query": "test-rhtap-.*-tenant" },
   {
    "name": "pods",
    "label": "Pod regexps to show",
    "query": ".*-build-container-pod,.*-clone-repository-pod,.*-init-pod,.*-show-sbom-pod,.*-show-summary-pod"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall for matching namespaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Matching namespaces RSS memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~'${namespace:raw}',container='',})",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='memory',namespace=~'${namespace:raw}'})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='memory',namespace=~'${namespace:raw}'})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Matching namespaces CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pod:container_cpu_usage:sum{namespace=~'${namespace:raw}'})",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='cpu',namespace=~'${namespace:raw}'})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='cpu',namespace=~'${namespace:raw}'})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Matching namespaces disk bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~'${namespace:raw}'}[5m]))",
     "legendFormat": "reads"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~'${namespace:raw}'}[5m])) * -1",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Matching namespaces network bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"\",namespace=~\"${namespace:raw}\"}[5m]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"\",namespace=~\"${namespace:raw}\"}[5m])) * -1",
     "legendFormat": "transmited"
    }
   ]
  },
  {
   "title": "Matching namespaces pods count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~'${namespace:raw}'})",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "Info about $pods in matching namespaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "pods",
   "collapsed": true,
   "panels": [
    {
     "title": "Average RSS memory usage of $pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(container_memory_working_set_bytes{namespace=~'${namespace:raw}',container='',pod=~'${pods:raw}'})",
       "legendFormat": "actual"
      },
      {
       "expr": "avg(kube_pod_resource_request{resource='memory',namespace=~'${namespace:raw}',pod=~'${pods:raw}'})",
       "legendFormat": "requests"
      },
      {
       "expr": "avg(kube_pod_resource_limit{resource='memory',namespace=~'${namespace:raw}',pod=~'${pods:raw}'})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Average CPU usage of $pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(pod:container_cpu_usage:sum{namespace=~'${namespace:raw}',pod=~'${pods:raw}'})",
       "legendFormat": "actual"
      },
      {
       "expr": "avg(kube_pod_resource_request{resource='cpu',namespace=~'${namespace:raw}',pod=~'${pods:raw}'})",
       "legendFormat": "requests"
      },
      {
       "expr": "avg(kube_pod_resource_limit{resource='cpu',namespace=~'${namespace:raw}',pod=~'${pods:raw}'})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Average disk bytes of $pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg(rate(container_fs_reads_bytes_total{namespace=~'${namespace:raw}', pod=~'${pods:raw}'}[5m]))",
       "legendFormat": "reads"
      },
      {
       "expr": "avg(rate(container_fs_writes_bytes_total{namespace=~'${namespace:raw}', pod=~'${pods:raw}'}[5m])) * -1",
       "legendFormat": "writes"
      }
     ]
    },
    {
     "title": "Average network bytes of $pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg(irate(container_network_receive_bytes_total{cluster=\"\",namespace=~\"${namespace:raw}\"}[5m]))",
       "legendFormat": "received"
      },
      {
       "expr": "avg(irate(container_network_transmit_bytes_total{cluster=\"\",namespace=~\"${namespace:raw}\"}[5m])) * -1",
       "legendFormat": "transmited"
      }
     ]
    },
    {
     "title": "Count of $pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_info{namespace=~'${namespace:raw}',pod=~'${pods:raw}'})",
       "legendFormat": "actual"
      }
     ]
    }
   ]
  }
 ]
}