{
 "title": "Performance: Konflux cluster overall",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Cluster - entities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace count by phase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_namespace_status_phase) by (phase)",
       "legendFormat": "{{ phase }} namespaces"
      }
     ]
    },
    {
     "title": "Pod count per state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{}) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Scheduler pending pods per queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum(scheduler_pending_pods) by (queue)",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "Attach/Detach controller PVCs count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum(attachdetach_controller_total_volumes{state=\"actual_state_of_world\"}) by (state)",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum(attachdetach_controller_total_volumes{state=\"desired_state_of_world\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "PVCs by status phase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster - resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\nnode_memory_MemTotal_bytes{}\n-\nnode_memory_MemFree_bytes{}\n-\nnode_memory_Buffers_bytes{}\n-\nnode_memory_Cached_bytes{}\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cluster CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cluster disk read and written bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total[5m]) + rate(node_disk_written_bytes_total[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Nodes network read and written bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total[5m]) + rate(node_network_transmit_bytes_total[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes - info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node count per condition",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{status=\"true\"}) by (condition)",
       "legendFormat": "{{condition}}"
      }
     ]
    },
    {
     "title": "Pod count per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(kube_pod_info{node!=\"\"}) by (node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Volume attachements per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(kube_volumeattachment_info) by (node)",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes - resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\nnode_memory_MemTotal_bytes{}\n-\nnode_memory_MemFree_bytes{}\n-\nnode_memory_Buffers_bytes{}\n-\nnode_memory_Cached_bytes{}\n) by (instance)\n",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Nodes CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Nodes disk read and written bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total[5m]) + rate(node_disk_written_bytes_total[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk IOPS per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_reads_completed_total[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Nodes network read and written bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total[5m]) + rate(node_network_transmit_bytes_total[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 namespaces by RSS memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(container_memory_rss{container!=\"POD\",name!=\"\"}) by (namespace))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Top 10 namespaces by CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(10, sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\"}) by (namespace))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Top 10 namepaces by disk usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(\n  rate(container_fs_reads_bytes_total{id!=\"\", device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=\"\"}[5m])\n  +\n  rate(container_fs_writes_bytes_total{id!=\"\", device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=\"\"}[5m])\n) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Top 10 namespaces by network usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(\n  rate(container_network_receive_bytes_total{}[5m])\n  +\n  rate(container_network_transmit_bytes_total{}[5m])\n) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Top 10 namespaces by deployments count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, count(kube_deployment_labels{}) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Top 10 namespaces by routes count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, count(openshift_route_info{}) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Top 10 namespaces by quota usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10,sum(kube_resourcequota{  type=\"used\"} / ignoring(type) ( kube_resourcequota{ type=\"hard\"} > 0)) by (resource,namespace) > 0.8)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tenants - resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 tenants by RSS memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(container_memory_rss{namespace=~\".*-tenant\",container!=\"POD\",name!=\"\"}) by (namespace))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Top 10 tenants by CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(10, sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=~\".*-tenant\"}) by (namespace))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Top 10 tenants by disk activity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(\n  rate(container_fs_reads_bytes_total{id!=\"\", device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=\"\", namespace=~\".*-tenant\"}[5m])\n  +\n  rate(container_fs_writes_bytes_total{id!=\"\", device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=\"\", namespace=~\".*-tenant\"}[5m])\n) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Top 10 tenants by network activity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(\n  irate(container_network_receive_bytes_total{namespace=~\".*-tenant\"}[5m])\n  +\n  irate(container_network_transmit_bytes_total{namespace=~\".*-tenant\"}[5m])\n) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tekton",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tekton Pipelines controller tasks runs throttle count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(tekton_pipelines_controller_running_taskruns_throttled_by_quota_count)",
       "legendFormat": "By quota count"
      },
      {
       "expr": "avg(tekton_pipelines_controller_running_taskruns_throttled_by_node_count)",
       "legendFormat": "By node count"
      }
     ]
    },
    {
     "title": "Running PipelineRuns and TaskRuns count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(tekton_pipelines_controller_running_pipelineruns_count)",
       "legendFormat": "PipelineRuns"
      },
      {
       "expr": "avg(tekton_pipelines_controller_running_taskruns_count)",
       "legendFormat": "TaskRuns"
      }
     ]
    },
    {
     "title": "Pipelines Controller leases distribution",
     "type": "timeseries",
     "description": "In each bucket, we have 8 leases. These leases should be distributed over more than 1 Pipelines controller replicas pods. If they are not, we might need Infra team intervention.\n\nDashed lines shows \"health\" intervals: if it is 0 or 1, call Infra team (we have alert for that); if it is 2, it is not giving good performance; 3 or 4 should be OK even during peaks.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(count by (lease_holder) (kube_lease_owner{lease=~\"tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.reconciler..*\", lease_holder!=\"\"}))",
       "legendFormat": "PipelineRun reconciler"
      },
      {
       "expr": "count(count by (lease_holder) (kube_lease_owner{lease=~\"tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.taskrun.reconciler..*\", lease_holder!=\"\"}))",
       "legendFormat": "TaskRun reconciler"
      },
      {
       "expr": "count(count by (lease_holder) (kube_lease_owner{lease=~\"tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.resolutionrequest.reconciler..*\", lease_holder!=\"\"}))",
       "legendFormat": "ResolutionRequest reconciler"
      }
     ]
    },
    {
     "title": "Tekton Resolver leases distribution",
     "type": "timeseries",
     "description": "In each bucket, we have 4 leases. These leases should be distributed over more than 1 Resolver replicas pods. If they are not, we might need Infra team intervention.\n\nDashed lines shows \"health\" intervals: if it is 0 or 1, call Infra team (we might have an alert for that: https://issues.redhat.com/browse/KONFLUX-5297); if it is 2, it is not giving good performance; 3 or 4 should be OK even during peaks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(count by (lease_holder) (kube_lease_owner{lease=~\"controller.tektonresolverframework.bundleresolver..*\", lease_holder!=\"\"}))",
       "legendFormat": "Bundle resolver"
      },
      {
       "expr": "count(count by (lease_holder) (kube_lease_owner{lease=~\"controller.tektonresolverframework.cluster..*\", lease_holder!=\"\"}))",
       "legendFormat": "Cluster resolver"
      },
      {
       "expr": "count(count by (lease_holder) (kube_lease_owner{lease=~\"controller.tektonresolverframework.git..*\", lease_holder!=\"\"}))",
       "legendFormat": "Git resolver"
      },
      {
       "expr": "count(count by (lease_holder) (kube_lease_owner{lease=~\"controller.tektonresolverframework.http..*\", lease_holder!=\"\"}))",
       "legendFormat": "Http resolver"
      },
      {
       "expr": "count(count by (lease_holder) (kube_lease_owner{lease=~\"controller.tektonresolverframework.hub..*\", lease_holder!=\"\"}))",
       "legendFormat": "Hub resolver"
      }
     ]
    },
    {
     "title": "Pipelines controller workqueue depth by queue name",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(tekton_pipelines_controller_workqueue_depth) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Finished PipelineRun and TaskRun count by status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tekton_pipelines_controller_pipelinerun_duration_seconds_count[1h])) by (status)",
       "legendFormat": "{{status}} PipelineRuns"
      },
      {
       "expr": "sum(rate(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds_count[1h])) by (status)",
       "legendFormat": "{{status}} TaskRuns"
      }
     ]
    },
    {
     "title": "Failed PipelineRuns by pipeline name",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum(rate(tekton_pipelines_controller_pipelinerun_duration_seconds_count{status=\"failed\"}[1h])) by (pipeline))",
       "legendFormat": "{{pipeline}} PipelineRuns"
      }
     ]
    },
    {
     "title": "Succeeded PipelineRuns by pipeline name",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum(rate(tekton_pipelines_controller_pipelinerun_duration_seconds_count{status=\"success\"}[1h])) by (pipeline))",
       "legendFormat": "{{pipeline}} PipelineRuns"
      }
     ]
    },
    {
     "title": "Succeeded TaskRuns by task name",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum(rate(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds_count{status=\"success\"}[1h])) by (task))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed TaskRuns by task name",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum(rate(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds_count{status=\"failed\"}[1h])) by (task))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pipelines controller client latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(tekton_pipelines_controller_client_latency_sum[5m]) / rate(tekton_pipelines_controller_client_latency_count[5m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Etcd average request duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(etcd_request_duration_seconds_sum{}[5m])) / sum(rate(etcd_request_duration_seconds_count[5m]))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tekton by namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 namespaces by average PipelineRun duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "topk(10,\n    sum(rate(tekton_pipelines_controller_pipelinerun_duration_seconds_sum{namespace=~\".*-tenant\"}[1h])) by (namespace)\n    /\n    sum(rate(tekton_pipelines_controller_pipelinerun_duration_seconds_count{namespace=~\".*-tenant\"}[1h])) by (namespace)\n)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Top 10 namespaces by average TaskRun duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10,\n    sum(rate(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds_sum{namespace=~\".*-tenant\"}[1h])) by (namespace)\n    /\n    sum(rate(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds_count{namespace=~\".*-tenant\"}[1h])) by (namespace)\n)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}