{
 "title": "Performance: Tenant resources usage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Tenant",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Most active tenants", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current quotas",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", type=\"hard\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Quota usage for namespace",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$namespace\", type=\"used\"} / ignoring(type) kube_resourcequota{namespace=\"$namespace\", type=\"hard\"}) by (resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actual CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actual RSS memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", container!=\"POD\", name!=\"\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PipelineRun duration rate by PipelineRun",
   "type": "timeseries",
   "description": "Unit here is duration burned by PipelineRuns in given Namespace in last hour",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum(rate(tekton_pipelines_controller_pipelinerun_duration_seconds_sum{namespace=\"$namespace\"}[60m])) by (pipeline) * 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PipelineRun count rate by PipelineRun",
   "type": "timeseries",
   "description": "Unit here is number of finished PipelineRuns in given Namespace in last hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(tekton_pipelines_controller_pipelinerun_duration_seconds_count{namespace=\"$namespace\"}[60m])) by (pipeline) * 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overal PipelineRun load on the cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Existing PipelineRun and TaskRun count by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tekton_pipelines_controller_pipelinerun_count[60m])) by (status)",
     "legendFormat": "{{status}} PipelineRun count"
    },
    {
     "expr": "sum(rate(tekton_pipelines_controller_taskrun_count[60m])) by (status)",
     "legendFormat": "{{status}} TaskRun count"
    }
   ]
  },
  {
   "title": "Running PipelineRuns and TaskRuns count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(tekton_pipelines_controller_running_pipelineruns_count)",
     "legendFormat": "Running PipelineRuns count"
    },
    {
     "expr": "sum(tekton_pipelines_controller_running_taskruns_count)",
     "legendFormat": "Running TaskRuns count"
    }
   ]
  }
 ]
}