{
 "title": "PipelineRuns and TaskRuns",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "PipelineRun and TaskRun count by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tekton_pipelines_controller_pipelinerun_count[10m])) by (status)",
     "legendFormat": "{{status}} PipelineRun count"
    },
    {
     "expr": "sum(rate(tekton_pipelines_controller_taskrun_count[10m])) by (status)",
     "legendFormat": "{{status}} TaskRun count"
    }
   ]
  },
  {
   "title": "Running PipelineRuns and TaskRuns count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tekton_pipelines_controller_running_pipelineruns_count)",
     "legendFormat": "Running PipelineRuns count"
    },
    {
     "expr": "sum(tekton_pipelines_controller_running_taskruns_count)",
     "legendFormat": "Running TaskRuns count"
    }
   ]
  },
  {
   "title": "PipelineRun duration rate by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(tekton_pipelines_controller_pipelinerun_duration_seconds_sum[10m])) by (exported_namespace)",
     "legendFormat": "PipelineRun duration rate"
    }
   ]
  },
  {
   "title": "TaskRun duration rate by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tekton_pipelines_controller_pipelinerun_taskrun_duration_seconds_sum[10m])) by (exported_namespace)",
     "legendFormat": "TaskRun duration rate"
    }
   ]
  }
 ]
}